version: "3.7"

services:

  dev-server:
    build:
      context: ./dev-server/docker
    container_name: 'server'
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./www:/app
    working_dir: /app
    env_file:
      - .env


  cli:
    build:
      context: ./cli/docker
    container_name: 'cli'
    volumes:
      - ./www:/app
    working_dir: /app
    env_file:
      - .env


  rabbit:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root





